version: "3.9"

services:
  sojo-weather-api:
    container_name: local-server
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/sojo-weather-api
    env_file:
      - .env
    ports:
      - "8000:8000"  # access API docs using http://localhost:8000/docs
