from src.models import TransformedCurrentWeatherSchema

VALID_ORIGINAL_RESPONSE = {
    "location": {
        "name": "Boston",
        "region": "Massachusetts",
        "country": "United States of America",
        "lat": 42.36,
        "lon": -71.06,
        "tz_id": "America/New_York",
        "localtime_epoch": 1726143137,
        "localtime": "2024-09-12 08:12",
    },
    "current": {
        "last_updated_epoch": 1726142400,
        "last_updated": "2024-09-12 08:00",
        "temp_c": 15.6,
        "temp_f": 60.1,
        "is_day": 1,
        "condition": {
            "text": "Partly cloudy",
            "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
            "code": 1003,
        },
        "wind_mph": 3.8,
        "wind_kph": 6.1,
        "wind_degree": 230,
        "wind_dir": "SW",
        "pressure_mb": 1024,
        "pressure_in": 30.25,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 78,
        "cloud": 25,
        "feelslike_c": 15.6,
        "feelslike_f": 60.1,
        "windchill_c": 17.3,
        "windchill_f": 63.1,
        "heatindex_c": 17.3,
        "heatindex_f": 63.2,
        "dewpoint_c": 7,
        "dewpoint_f": 44.5,
        "vis_km": 16,
        "vis_miles": 9,
        "uv": 5,
        "gust_mph": 7.6,
        "gust_kph": 12.3,
    },
}

INVALID_ORIGINAL_RESPONSE = {
    "location": {
        "name": "Tokyo",
        "region": "Tokyo",
        "country": "Japan",
        "lat": 35.69,
        "lon": 139.69,
        "tz_id": "Asia/Tokyo",
        "localtime_epoch": 1726143185,
        "localtime": "2024-09-12 21:13",
    },
    "current": {
        "last_updated_epoch": 1726142400,
        "last_updated": "2024-09-12 21:00",
        "temp_c": 29.4,
        "temp_f": 84.9,
        "is_day": 0,
        "condition": {
            "text": -1,  # Should be string
            "icon": "//cdn.weatherapi.com/weather/64x64/night/116.png",
            "code": 1003,
        },
        # missing wind speed
        "wind_degree": 180,
        "wind_dir": "S",
        "pressure_mb": 1013,
        "pressure_in": 29.91,
        "precip_mm": 0,
        "precip_in": 0,
        "humidity": 84,
        "cloud": 25,
        "feelslike_c": 34.2,
        "feelslike_f": 93.6,
        "windchill_c": 28.8,
        "windchill_f": 83.9,
        "heatindex_c": 33,
        "heatindex_f": 91.3,
        "dewpoint_c": 23.5,
        "dewpoint_f": 74.3,
        "vis_km": 10,
        "vis_miles": 6,
        "uv": 1,
        "gust_mph": 22.4,
        "gust_kph": 36.1,
    },
}


EXPECTED_TRANSFORMED_DATA = TransformedCurrentWeatherSchema(
    location_name="Boston",
    current_temperature={"celsius": 15.6, "fahrenheit": 60.1},
    wind_speed={"kph": 6.1, "mph": 6.1},
    description="Partly cloudy",
)
